-- AlterTable
ALTER TABLE "Department" ADD COLUMN     "totalWeight" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalWeightedSum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "avgRating" SET DEFAULT 0;
